addons:
  apt:
    packages:
    - libxml-xpath-perl
sudo: required

language: java
jdk: openjdk8
before_install:
- "./src/main/scripts/ci/before-install.sh"
- "./src/main/scripts/cd/before-deploy.sh"
after_success: "./src/main/scripts/ci/after-success.sh"
deploy:
- provider: script
  script: mvn -P release deploy -DskipTests=true -B -V -s travis-settings.xml
  on:
    branch: develop
- provider: script
  script:
  - "./src/main/scripts/cd/deploy.sh"
  on:
    branch: master